import React, { useState, useMemo } from 'react';
import { Copy, Download, FileText, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

const DISCLAIMER_TEXT = `Disclaimer: This output is generated by a demonstration tool for the Universal Command Protocol (UCP). Do not paste confidential or personal data. AI results can vary by model/provider and must be validated independently. This is not legal, medical, or financial advice. Deterministic formatting is enforced where possible, but identical responses are not guaranteed across all AI systems.`;

const OUTPUT_SCHEMA = {
  "ucp_version": "1.0",
  "input_command": "",
  "intent_packet": "",
  "compiled_codes": [],
  "detokenized_steps": [
    {
      "index": 1,
      "from_code": "",
      "action": "",
      "target": "",
      "params": {}
    }
  ],
  "execution_result": {
    "status": "ok",
    "artifacts": [
      { "type": "text", "name": "summary", "content": "" }
    ]
  },
  "assumptions": [],
  "missing_inputs": [],
  "notes": ""
};

async function sha256(message) {
  const msgBuffer = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

export default function PromptPackGenerator({ 
  inputCommand, 
  intentPacket, 
  compiledCodes, 
  detokenizedSteps 
}) {
  const [mode, setMode] = useState('neutral'); // 'neutral' or 'strict'
  const [includeSampleData, setIncludeSampleData] = useState(false);
  const [includeDisclaimer, setIncludeDisclaimer] = useState(true);
  const [sampleData, setSampleData] = useState('');
  const [copied, setCopied] = useState(false);

  const promptPack = useMemo(async () => {
    const checksumInput = `${inputCommand}${intentPacket}${JSON.stringify(detokenizedSteps)}`;
    const checksum = await sha256(checksumInput);
    
    let pack = '';

    // Disclaimer
    if (includeDisclaimer) {
      pack += `${DISCLAIMER_TEXT}\n\n`;
      pack += `═══════════════════════════════════════════════════════════════\n\n`;
    }

    // Reproducibility header
    if (mode === 'strict') {
      pack += `REPRODUCIBILITY INSTRUCTIONS:\n`;
      pack += `- Use lowest temperature setting (or temperature=0 equivalent)\n`;
      pack += `- Follow the output schema exactly\n`;
      pack += `- Do NOT be creative or add narrative\n`;
      pack += `- Return ONLY valid JSON\n\n`;
    } else {
      pack += `REPRODUCIBILITY GUIDANCE:\n`;
      pack += `- Use deterministic settings if possible (low temperature)\n`;
      pack += `- Follow the structure provided\n`;
      pack += `- Avoid creative additions\n\n`;
    }

    pack += `═══════════════════════════════════════════════════════════════\n\n`;

    // Original input
    pack += `ORIGINAL INPUT COMMAND:\n${inputCommand}\n\n`;

    // UCP Intent Packet
    pack += `UCP INTENT PACKET:\n${intentPacket}\n\n`;

    // Compiled codes
    pack += `COMPILED CODES:\n${compiledCodes.join(', ')}\n\n`;

    // Detokenized steps
    pack += `DETOKENIZED STEPS (Execute in order):\n`;
    detokenizedSteps.forEach((step, idx) => {
      pack += `${idx + 1}. [${step.from || 'N/A'}] ${step.action} @ ${step.target}\n`;
      if (step.params && Object.keys(step.params).length > 0) {
        pack += `   Params: ${JSON.stringify(step.params)}\n`;
      }
    });
    pack += `\n`;

    // Sample data (optional)
    if (includeSampleData && sampleData.trim()) {
      pack += `SAMPLE DATA PROVIDED:\n`;
      pack += `\`\`\`\n${sampleData}\n\`\`\`\n\n`;
      pack += `INSTRUCTION: Use ONLY the above sample data. Do not simulate or invent data.\n\n`;
    } else if (includeSampleData) {
      pack += `SAMPLE DATA: None provided. Flag as missing_inputs.\n\n`;
    }

    // Deterministic constraints
    pack += `═══════════════════════════════════════════════════════════════\n\n`;
    pack += `DETERMINISTIC CONSTRAINTS (MUST FOLLOW):\n`;
    pack += `1. Do NOT invent steps beyond the listed steps above\n`;
    pack += `2. Do NOT reorder steps\n`;
    pack += `3. If data is missing, return "unknown" or flag in missing_inputs\n`;
    pack += `4. Use concise, non-creative language (no storytelling)\n`;
    pack += `5. Return output in the exact JSON schema provided below\n\n`;

    // Output schema
    pack += `OUTPUT SCHEMA (Use this exact structure):\n`;
    pack += `\`\`\`json\n${JSON.stringify(OUTPUT_SCHEMA, null, 2)}\n\`\`\`\n\n`;

    // Verification
    pack += `VERIFICATION:\n`;
    pack += `- Checksum (SHA-256): ${checksum}\n`;
    pack += `- Expected step count: ${detokenizedSteps.length}\n\n`;

    // Final instruction
    pack += `═══════════════════════════════════════════════════════════════\n\n`;
    if (mode === 'strict') {
      pack += `FINAL INSTRUCTION:\nReturn ONLY the JSON response. No additional text, no markdown formatting, no explanations. Just the JSON object matching the schema above.`;
    } else {
      pack += `FINAL INSTRUCTION:\nProvide your response in the JSON format specified above. Include any assumptions made in the "assumptions" field.`;
    }

    return pack;
  }, [inputCommand, intentPacket, compiledCodes, detokenizedSteps, mode, includeDisclaimer, includeSampleData, sampleData]);

  const [packText, setPackText] = useState('');

  // Generate pack on mount and when dependencies change
  React.useEffect(() => {
    promptPack.then(setPackText);
  }, [promptPack]);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(packText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      alert('Failed to copy to clipboard');
    }
  };

  const downloadTxt = () => {
    const blob = new Blob([packText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ucp-prompt-pack.txt';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const downloadJson = () => {
    const jsonObj = {
      disclaimer: includeDisclaimer ? DISCLAIMER_TEXT : null,
      mode: mode,
      input_command: inputCommand,
      intent_packet: intentPacket,
      compiled_codes: compiledCodes,
      detokenized_steps: detokenizedSteps,
      sample_data: includeSampleData ? sampleData : null,
      output_schema: OUTPUT_SCHEMA
    };

    const blob = new Blob([JSON.stringify(jsonObj, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ucp-prompt-pack.json';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  if (!inputCommand || compiledCodes.length === 0) {
    return (
      <div className="bg-gray-800 rounded-lg border border-gray-700 p-5">
        <h3 className="font-bold text-white flex items-center gap-2 mb-3">
          <FileText className="h-4 w-4" /> Portable Prompt Pack
        </h3>
        <p className="text-sm text-gray-500">Run a command first to generate a prompt pack.</p>
      </div>
    );
  }

  return (
    <div className="bg-gray-800 rounded-lg border border-gray-700 p-5">
      <h3 className="font-bold text-white flex items-center gap-2 mb-4">
        <FileText className="h-4 w-4" /> Portable Prompt Pack
      </h3>

      {/* Mode toggle */}
      <div className="mb-4">
        <label className="text-xs text-gray-400 mb-2 block">Pack Mode</label>
        <div className="flex gap-2">
          <button
            onClick={() => setMode('neutral')}
            className={`flex-1 px-3 py-2 rounded text-xs font-medium transition-all ${
              mode === 'neutral'
                ? 'bg-blue-600 text-white'
                : 'bg-gray-900 text-gray-400 hover:bg-gray-700'
            }`}
          >
            AI-Neutral
          </button>
          <button
            onClick={() => setMode('strict')}
            className={`flex-1 px-3 py-2 rounded text-xs font-medium transition-all ${
              mode === 'strict'
                ? 'bg-purple-600 text-white'
                : 'bg-gray-900 text-gray-400 hover:bg-gray-700'
            }`}
          >
            Strict JSON
          </button>
        </div>
      </div>

      {/* Options */}
      <div className="space-y-2 mb-4">
        <label className="flex items-center gap-2 text-xs text-gray-300 cursor-pointer">
          <input
            type="checkbox"
            checked={includeDisclaimer}
            onChange={(e) => setIncludeDisclaimer(e.target.checked)}
            className="rounded"
          />
          Include Disclaimer (recommended)
        </label>
        <label className="flex items-center gap-2 text-xs text-gray-300 cursor-pointer">
          <input
            type="checkbox"
            checked={includeSampleData}
            onChange={(e) => setIncludeSampleData(e.target.checked)}
            className="rounded"
          />
          Include Sample Data
        </label>
      </div>

      {/* Sample data textarea */}
      {includeSampleData && (
        <div className="mb-4">
          <label className="text-xs text-gray-400 mb-2 block">Sample Data (optional)</label>
          <Textarea
            value={sampleData}
            onChange={(e) => setSampleData(e.target.value)}
            placeholder="Paste sample data here (e.g., CSV, JSON, or text)..."
            className="bg-gray-900 border-gray-700 text-white text-xs font-mono h-24"
          />
        </div>
      )}

      {/* Preview */}
      <div className="mb-4">
        <label className="text-xs text-gray-400 mb-2 block">Pack Preview</label>
        <div className="bg-gray-900 border border-gray-700 rounded p-3 text-xs font-mono text-gray-300 h-48 overflow-auto whitespace-pre-wrap">
          {packText}
        </div>
      </div>

      {/* Action buttons */}
      <div className="flex gap-2 flex-wrap">
        <Button
          onClick={copyToClipboard}
          className="bg-green-600 hover:bg-green-700 text-white flex items-center gap-2"
          size="sm"
        >
          {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
          {copied ? 'Copied!' : 'Copy'}
        </Button>
        <Button
          onClick={downloadTxt}
          variant="outline"
          className="border-gray-600 hover:bg-gray-700 flex items-center gap-2"
          size="sm"
        >
          <Download className="h-4 w-4" />
          Download TXT
        </Button>
        <Button
          onClick={downloadJson}
          variant="outline"
          className="border-gray-600 hover:bg-gray-700 flex items-center gap-2"
          size="sm"
        >
          <Download className="h-4 w-4" />
          Download JSON
        </Button>
      </div>
    </div>
  );
}