import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@2.5.2';

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const { donationId } = await req.json();

        // Fetch donation
        const donations = await base44.asServiceRole.entities.Donation.filter({ id: donationId });
        if (!donations || donations.length === 0) {
            return Response.json({ error: 'Donation not found' }, { status: 404 });
        }

        const donation = donations[0];

        // Fetch profile
        const profiles = await base44.asServiceRole.entities.Profile.filter({ id: donation.profileId });
        if (!profiles || profiles.length === 0) {
            return Response.json({ error: 'Profile not found' }, { status: 404 });
        }

        const profile = profiles[0];

        // Generate PDF
        const doc = new jsPDF();

        // Header
        doc.setFontSize(24);
        doc.setTextColor(37, 99, 235); // Blue
        doc.text('Payment Receipt', 20, 30);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text('Cloud Collect', 20, 38);

        // Transaction Details
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Transaction Details', 20, 55);

        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        
        let y = 68;
        const lineHeight = 8;

        doc.text(`Recipient: ${profile.publicName}`, 20, y);
        y += lineHeight;
        
        doc.text(`Donor: ${donation.donorName || 'Anonymous'}`, 20, y);
        y += lineHeight;

        if (donation.donorEmail) {
            doc.text(`Email: ${donation.donorEmail}`, 20, y);
            y += lineHeight;
        }

        doc.text(`Amount: $${donation.grossAmount.toFixed(2)}`, 20, y);
        y += lineHeight;

        doc.text(`Date: ${new Date(donation.created_date).toLocaleDateString()}`, 20, y);
        y += lineHeight;

        doc.text(`Transaction ID: ${donation.id}`, 20, y);
        y += lineHeight + 5;

        if (donation.donorMessage) {
            doc.text(`Message: ${donation.donorMessage}`, 20, y);
            y += lineHeight + 5;
        }

        // Tax Information
        doc.setDrawColor(200, 200, 200);
        doc.line(20, y, 190, y);
        y += 10;

        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text('For Your Records', 20, y);
        y += 10;

        doc.setFontSize(10);
        doc.setTextColor(80, 80, 80);
        const taxText = doc.splitTextToSize(
            'This is a receipt for your peer-to-peer payment through Cloud Collect. Please consult with your tax advisor to determine if this contribution qualifies for any tax benefits in your jurisdiction. Keep this receipt for your records.',
            170
        );
        doc.text(taxText, 20, y);

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by Cloud Collect', 20, 280);
        doc.text(new Date().toLocaleDateString(), 170, 280);

        const pdfBytes = doc.output('arraybuffer');

        return new Response(pdfBytes, {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename=receipt-${donation.id}.pdf`
            }
        });

    } catch (error) {
        console.error('Receipt generation error:', error);
        return Response.json({ 
            error: 'Failed to generate receipt',
            details: error.message 
        }, { status: 500 });
    }
});