import React from "react";
import { Card } from "@/components/ui/card";
import { BookOpen, Zap, Calculator, AlertCircle, CheckCircle } from "lucide-react";

export default function Methodology() {
  return (
    <div className="p-6 space-y-8 max-w-5xl mx-auto">
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-3 mb-4">
          <BookOpen className="w-10 h-10 text-emerald-400" />
        </div>
        <h1 className="text-4xl font-bold text-white mb-4">Methodology</h1>
        <p className="text-slate-400 text-lg">Understanding how we measure and calculate energy consumption</p>
      </div>

      <Card className="bg-slate-800/50 border-slate-700 backdrop-blur-md p-8">
        <div className="flex items-center gap-3 mb-4">
          <Zap className="w-6 h-6 text-yellow-400" />
          <h2 className="text-2xl font-bold text-white">Energy Measurement</h2>
        </div>
        <div className="space-y-4 text-slate-300">
          <p>
            Aura Energy tracks AI inference energy consumption through two methods:
          </p>
          <div className="pl-6 space-y-3">
            <div>
              <h3 className="font-semibold text-white flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-emerald-400" />
                Measured Energy
              </h3>
              <p className="text-sm">
                Direct measurements from hardware telemetry (GPU power sensors, system monitors). 
                This is the most accurate method and is labeled as "measured" in the dashboard.
              </p>
            </div>
            <div>
              <h3 className="font-semibold text-white flex items-center gap-2">
                <Calculator className="w-4 h-4 text-cyan-400" />
                Estimated Energy
              </h3>
              <p className="text-sm">
                When direct measurements aren't available, we estimate energy using the formula:
              </p>
              <div className="bg-slate-900 rounded-lg p-4 mt-2 font-mono text-xs">
                Energy (Wh) = Power (W) × Time (hours)
                <br />
                Energy (Wh) = avgPowerW × (latencyMs / 1000 / 3600)
              </div>
              <p className="text-sm mt-2">
                The average power (avgPowerW) is sourced from model profiles. If no profile exists, 
                we use a conservative default of 150W. Estimated values are clearly labeled.
              </p>
            </div>
          </div>
        </div>
      </Card>

      <Card className="bg-slate-800/50 border-slate-700 backdrop-blur-md p-8">
        <div className="flex items-center gap-3 mb-4">
          <Calculator className="w-6 h-6 text-cyan-400" />
          <h2 className="text-2xl font-bold text-white">Token Measurement</h2>
        </div>
        <div className="space-y-4 text-slate-300">
          <p>
            Token counts are obtained directly from the AI model's response metadata:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Prompt Tokens:</strong> Input tokens sent to the model</li>
            <li><strong>Completion Tokens:</strong> Output tokens generated by the model</li>
            <li><strong>Total Tokens:</strong> Sum of prompt and completion tokens</li>
          </ul>
          <p className="text-sm">
            Token counts are provided by the inference API (OpenAI, Ollama, Anthropic, etc.) 
            and represent the actual number of tokens processed.
          </p>
        </div>
      </Card>

      <Card className="bg-slate-800/50 border-slate-700 backdrop-blur-md p-8">
        <div className="flex items-center gap-3 mb-4">
          <Zap className="w-6 h-6 text-emerald-400" />
          <h2 className="text-2xl font-bold text-white">CO₂ Emissions</h2>
        </div>
        <div className="space-y-4 text-slate-300">
          <p>
            Carbon emissions are calculated using grid carbon intensity:
          </p>
          <div className="bg-slate-900 rounded-lg p-4 font-mono text-xs">
            CO₂ (g) = (Energy (Wh) / 1000) × Grid Intensity (g/kWh)
          </div>
          <p className="text-sm mt-2">
            We use a default grid intensity of 400 g CO₂/kWh (approximate US average). 
            This can be customized in the Admin panel for more accurate regional calculations.
          </p>
        </div>
      </Card>

      <Card className="bg-slate-800/50 border-slate-700 backdrop-blur-md p-8">
        <div className="flex items-center gap-3 mb-4">
          <BookOpen className="w-6 h-6 text-purple-400" />
          <h2 className="text-2xl font-bold text-white">Savings Calculations</h2>
        </div>
        <div className="space-y-4 text-slate-300">
          <p>
            Savings percentages compare baseline runs against UCP-optimized runs:
          </p>
          <div className="bg-slate-900 rounded-lg p-4 font-mono text-xs">
            Savings % = ((Baseline - UCP) / Baseline) × 100
          </div>
          <p className="text-sm mt-2">
            This formula applies to tokens, energy, latency, and cost. Positive percentages 
            indicate reductions (savings), while negative values indicate increases.
          </p>
        </div>
      </Card>

      <Card className="bg-gradient-to-br from-yellow-500/10 to-orange-500/10 border-yellow-500/30 backdrop-blur-md p-8">
        <div className="flex items-start gap-3">
          <AlertCircle className="w-6 h-6 text-yellow-400 flex-shrink-0 mt-1" />
          <div className="space-y-2 text-slate-300">
            <h2 className="text-xl font-bold text-white">Important Disclaimers</h2>
            <ul className="list-disc pl-6 space-y-2 text-sm">
              <li>
                <strong>Estimated vs Measured:</strong> Always check the energy mode label. 
                Estimated values provide approximations and may not reflect actual consumption.
              </li>
              <li>
                <strong>Model Variability:</strong> Energy consumption varies by hardware, 
                batch size, quantization, and other factors.
              </li>
              <li>
                <strong>Grid Intensity:</strong> CO₂ calculations depend on your region's 
                energy mix. Update the grid intensity setting for accuracy.
              </li>
              <li>
                <strong>Comparison Validity:</strong> Only compare sessions with similar 
                conditions (same model, similar input complexity).
              </li>
            </ul>
          </div>
        </div>
      </Card>

      <Card className="bg-slate-800/50 border-slate-700 backdrop-blur-md p-8">
        <h2 className="text-2xl font-bold text-white mb-4">Data Sources</h2>
        <div className="space-y-3 text-slate-300 text-sm">
          <p>• <strong>Token Counts:</strong> Model API responses (OpenAI, Anthropic, Ollama, etc.)</p>
          <p>• <strong>Latency:</strong> Wall-clock time measured by the client application</p>
          <p>• <strong>Energy (Measured):</strong> NVIDIA SMI, Intel RAPL, system power sensors</p>
          <p>• <strong>Energy (Estimated):</strong> Model profiles and calculated estimates</p>
          <p>• <strong>Model Profiles:</strong> Maintained in Admin panel, sourced from benchmarks</p>
        </div>
      </Card>
    </div>
  );
}